services:
  - type: web
    name: fitia
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        value: false
      - key: NEXT_PUBLIC_API_URL
        value: false
      - key: SERVER_API_URL
        value: false
      - key: DATABASE_URL
        sync: false
      - key: BETTER_AUTH_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
