services:
  - type: web
    name: fitia-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: PORT
        value: 3333
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: API_BASE_URL
        sync: false
      - key: WEB_APP_BASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_GENERATIVE_AI_API_KEY
        sync: false
