// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

import { existsSync } from "node:fs";
import { defineConfig } from "prisma/config";

const isRunningInDocker = existsSync("/.dockerenv");

const getDatabaseUrl = () => {
  const databaseUrl = process.env["DATABASE_URL"];

  if (!databaseUrl) {
    return databaseUrl;
  }

  const parsedUrl = new URL(databaseUrl);

  if (parsedUrl.hostname === "postgres") {
    parsedUrl.port = isRunningInDocker ? "5432" : "5433";
    parsedUrl.hostname = isRunningInDocker ? "postgres" : "localhost";
  }

  return parsedUrl.toString();
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
